# Generated by Django 5.1.1 on 2025-05-28 09:38

import django.contrib.postgres.fields
import django.db.models.deletion
import picklefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orcid', models.CharField(blank=True, max_length=2000)),
                ('file', models.FileField(upload_to='user_files')),
                ('title', models.CharField(blank=True, default='', max_length=2000)),
                ('structure_notes', models.TextField(blank=True, default='')),
                ('description', models.CharField(blank=True, default='', max_length=2000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('dwca_url', models.CharField(blank=True, max_length=2000)),
                ('gbif_url', models.CharField(blank=True, max_length=2000)),
                ('user_language', models.CharField(blank=True, max_length=100)),
                ('dwc_core', models.CharField(blank=True, choices=[('event_occurrences', 'Event'), ('occurrence', 'Occurrence'), ('taxonomy', 'Taxonomy')], max_length=30)),
                ('dwc_extensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('simple_multimedia', 'Simple Multimedia'), ('measurement_or_fact', 'Measurement Or Fact'), ('gbif_releve', 'Gbif Releve')], max_length=500), blank=True, null=True, size=None)),
            ],
            options={
                'ordering': ['created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('busy_thinking', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dataset')),
            ],
            options={
                'ordering': ['created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('openai_obj', models.JSONField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agent')),
            ],
            options={
                'ordering': ['created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('df', picklefield.fields.PickledObjectField(editable=False)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dataset')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='tables',
            field=models.ManyToManyField(blank=True, to='api.table'),
        ),
        migrations.AddField(
            model_name='agent',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.task'),
        ),
    ]
