# Generated by Django 6.0.4 on 2026-07-28 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_dataset_source_accounting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetAttentionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Waiting for attention'), ('ready', 'Ready to send'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('attention_kind', models.CharField(blank=True, choices=[('needs_input', 'Needs input'), ('ready', 'Package ready'), ('published', 'Published')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attention_notification', to='api.dataset')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
