# Generated by Django 6.0.4 on 2026-09-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_dataset_provisional_dwca_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='dwca_role',
            field=models.CharField(blank=True, default='', editable=False, max_length=100),
        ),
    ]
