# Generated by Django 6.0.4 on 2026-09-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_table_dwca_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='dwca_role',
        ),
    ]
