# Generated by Django 6.0.4 on 2026-09-29 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_table_dwca_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonNameMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table', models.CharField(max_length=200)),
                ('context_column', models.CharField(blank=True, default='', max_length=200)),
                ('verbatim_label', models.TextField()),
                ('context_key', models.CharField(blank=True, default='', max_length=200)),
                ('context_note', models.TextField(blank=True)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('query', models.JSONField(default=dict, help_text='Name and classification hints sent to the matcher.')),
                ('preprocessing_note', models.TextField(blank=True)),
                ('identification_qualifier', models.CharField(blank=True, max_length=100)),
                ('match', models.JSONField(default=dict, help_text='Summarised GBIF v2 COL XR match.')),
                ('review_aids', models.JSONField(blank=True, default=dict)),
                ('col_release', models.JSONField(blank=True, default=dict)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted a COL name'), ('not_in_col', "Correct name, not in GBIF's COL copy"), ('keep_original', 'Keep the original data unchanged')], default='pending', max_length=20)),
                ('decided_usage', models.JSONField(blank=True, default=dict)),
                ('decided_query', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxon_matches', to='api.dataset')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_count', 'verbatim_label', 'id'],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'source_table', 'context_column', 'verbatim_label', 'context_key'), name='unique_taxon_label_per_source_context')],
            },
        ),
    ]
