# Generated by Django 6.0.4 on 2026-09-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_taxon_name_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonnamematch',
            name='verbatim_column',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
