# Generated by Django 6.0.4 on 2026-10-02 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_taxon_match_verbatim_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='workflow_type',
            field=models.CharField(choices=[('publication', 'Publish a dataset'), ('dwca_conversion', 'Convert a Darwin Core Archive')], default='publication', max_length=30),
        ),
        migrations.CreateModel(
            name='DwcConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('inspecting', 'Inspecting'), ('review', 'Review'), ('reviewing', 'Reviewing'), ('converting', 'Converting'), ('complete', 'Complete'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('plan', models.JSONField(default=dict)),
                ('decisions', models.JSONField(default=dict)),
                ('suggestions', models.JSONField(default=list)),
                ('report', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('output_file', models.FileField(blank=True, upload_to='user_files/conversions')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion', to='api.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='DwcConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='inspect', max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='api.dwcconversion')),
            ],
        ),
    ]
