# Generated by Django 6.0.4 on 2026-10-02 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_dwca_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiusage',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openai_usage_records', to='api.agent'),
        ),
    ]
