# Generated by Django 6.0.4 on 2026-10-04 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_conversion_conflicts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dwcconversion',
            name='advice_reviewed',
        ),
        migrations.RemoveField(
            model_name='dwcconversion',
            name='suggestions',
        ),
        migrations.AddField(
            model_name='dwcconversion',
            name='review',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dwcconversionjob',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConversionSpendReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('response_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_reservations', to='api.dwcconversion')),
            ],
        ),
        migrations.CreateModel(
            name='DwcConversionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('kind', models.CharField(blank=True, max_length=20)),
                ('content', models.TextField(blank=True)),
                ('plan_id', models.CharField(blank=True, max_length=64)),
                ('asked', models.JSONField(blank=True, default=list)),
                ('proposals', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('answers_through', models.PositiveBigIntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('response_id', models.CharField(blank=True, max_length=200)),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.dwcconversion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DwcConversionDecisionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_id', models.CharField(max_length=64)),
                ('decision_id', models.CharField(max_length=500)),
                ('value', models.CharField(blank=True, max_length=500)),
                ('previous_value', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(choices=[('user', 'User'), ('ai-reviewer', 'Ai Reviewer'), ('chat', 'Chat'), ('system', 'System')], max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('reasoning_effort', models.CharField(blank=True, max_length=30)),
                ('response_id', models.CharField(blank=True, max_length=200)),
                ('confidence', models.CharField(blank=True, max_length=20)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('rationale', models.TextField(blank=True)),
                ('transcript', models.JSONField(blank=True, default=dict)),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_events', to='api.dwcconversion')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_events', to='api.dwcconversionmessage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
