# Generated by Django 6.0.4 on 2026-10-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_conversion_name_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwcconversion',
            name='metadata_sources',
            field=models.JSONField(default=dict),
        ),
    ]
