# Generated by Django 6.0.4 on 2026-10-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_conversion_metadata_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwcconversion',
            name='drop_unlinked_extension_rows',
            field=models.BooleanField(default=False),
        ),
    ]
