services:
  db:
    image: postgres:latest # To clear database: docker rm -v publishgpt-db-1
    shm_size: 5g
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
    platform: linux/amd64
  back-end:
    build: ./back-end
    # entrypoint: "tail -f /dev/null"
    entrypoint: "./manage.py runserver 0.0.0.0:8000"
    image: gbifnorway/publishgpt-back-end:latest
    volumes:
      - ./back-end:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./back-end/.env
  front-end:
    build: ./front-end
    image: gbifnorway/publishgpt-front-end:latest
    volumes:
      - ./front-end:/app
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    env_file:
      - ./front-end/.env
    depends_on:
        - back-end
    # command: ["tail", "-f", "/dev/null"]
    command: ["npm", "run", "dev"]
