version: '3'

services:
  db:
    image: postgres:latest # To clear database: docker rm -v publishgpt-db-1 
    shm_size: 5g
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
  back-end:
    build: ./back-end
    entrypoint: "tail -f /dev/null"  # python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    volumes:
      - ./back-end:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./back-end/.env
  front-end:
    build: ./front-end
    volumes:
      - ./front-end:/app
    entrypoint: npm run dev
    ports:
      - "3000:3000"
    env_file:
      - ./front-end/.env
    depends_on:
        - back-end
