services:
  db:
    image: postgres:latest # To clear database: docker rm -v chatipt-db-1
    shm_size: 5g
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
    platform: linux/amd64
  back-end: 
    # docker buildx build --platform linux/amd64 -t gbifnorway/chatipt-back-end:$(git rev-parse --short HEAD) -t gbifnorway/chatipt-back-end:latest --push .
    build: ./back-end
    image: gbifnorway/chatipt-back-end:latest
    volumes:
      - ./back-end:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./back-end/.env.dev
    environment:
      # ORCID OAuth2 credentials (override from env file if needed)
      - ORCID_CLIENT_ID=${ORCID_CLIENT_ID}
      - ORCID_CLIENT_SECRET=${ORCID_CLIENT_SECRET}
      # Optional: Create superuser on startup
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-}
  front-end: 
    # docker buildx build --platform linux/amd64 --build-arg NEXT_PUBLIC_BASE_API_URL=https://api.chatipt.svc.gbif.no/api -t gbifnorway/chatipt-front-end:$(git rev-parse --short HEAD) -t gbifnorway/chatipt-front-end:latest --push .
    build: ./front-end
    image: gbifnorway/chatipt-front-end:latest
    volumes:
      - ./front-end:/app
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    env_file:
      - ./front-end/.env
    depends_on:
        - back-end
    # command: ["tail", "-f", "/dev/null"]
    command: ["npm", "run", "dev"]
