from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Dict, Iterable, Tuple


_BASE_DIR = Path(__file__).resolve().parent
_TEMPLATES_ROOT = _BASE_DIR / "templates"


@dataclass(frozen=True)
class DarwinCoreSchema:
    key: str
    title: str
    spec_uri: str | None
    local_filename: str
    row_type: str
    terms: Tuple[str, ...]
    id_column: str | None = None

    @property
    def spec_path(self) -> str:
        if self.spec_uri:
            return self.spec_uri
        return str((_TEMPLATES_ROOT / self.local_filename).resolve())

    @property
    def normalized_terms(self) -> set[str]:
        return {term.lower() for term in self.terms}


class DarwinCoreCoreType(str, Enum):
    OCCURRENCE = "occurrence"
    EVENT = "event"
    TAXON = "taxon"

    def __str__(self) -> str:
        return self.value


class DarwinCoreExtensionType(str, Enum):
    MEASUREMENT_OR_FACT = "measurement_or_fact"
    DNA_DERIVED_DATA = "dna_derived_data"
    IDENTIFICATION = "identification"
    IDENTIFICATION_HISTORY = "identification_history"
    IDENTIFIER = "identifier"
    DESCRIPTION = "description"
    DISTRIBUTION = "distribution"
    MULTIMEDIA = "multimedia"
    REFERENCES = "references"
    RESOURCE_RELATION = "resource_relation"
    RESOURCE_RELATIONSHIP = "resource_relationship"
    SPECIES_PROFILE = "species_profile"
    TYPES_AND_SPECIMEN = "types_and_specimen"
    VERNACULAR_NAME = "vernacular_name"
    RELEVE = "releve"
    CHRONOMETRIC_AGE = "chronometric_age"

    def __str__(self) -> str:
        return self.value


CORE_SCHEMAS: Dict[DarwinCoreCoreType, DarwinCoreSchema] = {
    DarwinCoreCoreType.OCCURRENCE: DarwinCoreSchema(
        key="occurrence",
        title="Darwin Core Occurrence",
        spec_uri="https://rs.gbif.org/core/dwc_occurrence_2025-07-10.xml",
        local_filename="cores/dwc_occurrence_2025-07-10.xml",
        row_type="http://rs.tdwg.org/dwc/terms/Occurrence",
        terms=(
            "acceptedNameUsage",
            "acceptedNameUsageID",
            "accessRights",
            "associatedMedia",
            "associatedOccurrences",
            "associatedOrganisms",
            "associatedReferences",
            "associatedSequences",
            "associatedTaxa",
            "basisOfRecord",
            "bed",
            "behavior",
            "bibliographicCitation",
            "caste",
            "catalogNumber",
            "causeOfDeath",
            "class",
            "collectionCode",
            "collectionID",
            "continent",
            "coordinatePrecision",
            "coordinateUncertaintyInMeters",
            "country",
            "countryCode",
            "county",
            "cultivarEpithet",
            "dataGeneralizations",
            "datasetID",
            "datasetName",
            "dateIdentified",
            "day",
            "decimalLatitude",
            "decimalLongitude",
            "degreeOfEstablishment",
            "digitalSpecimenID",
            "discipline",
            "disposition",
            "dynamicProperties",
            "earliestAgeOrLowestStage",
            "earliestEonOrLowestEonothem",
            "earliestEpochOrLowestSeries",
            "earliestEraOrLowestErathem",
            "earliestPeriodOrLowestSystem",
            "endDayOfYear",
            "establishmentMeans",
            "eventDate",
            "eventID",
            "eventRemarks",
            "eventTime",
            "eventType",
            "family",
            "feedbackURL",
            "fieldNotes",
            "fieldNumber",
            "footprintSRS",
            "footprintSpatialFit",
            "footprintWKT",
            "formation",
            "fundingAttribution",
            "fundingAttributionID",
            "genericName",
            "genus",
            "geodeticDatum",
            "geologicalContextID",
            "georeferenceProtocol",
            "georeferenceRemarks",
            "georeferenceSources",
            "georeferenceVerificationStatus",
            "georeferencedBy",
            "georeferencedDate",
            "group",
            "habitat",
            "higherClassification",
            "higherGeography",
            "higherGeographyID",
            "highestBiostratigraphicZone",
            "identificationID",
            "identificationQualifier",
            "identificationReferences",
            "identificationRemarks",
            "identificationVerificationStatus",
            "identifiedBy",
            "identifiedByID",
            "individualCount",
            "informationWithheld",
            "infragenericEpithet",
            "infraspecificEpithet",
            "institutionCode",
            "institutionID",
            "island",
            "islandGroup",
            "kingdom",
            "language",
            "latestAgeOrHighestStage",
            "latestEonOrHighestEonothem",
            "latestEpochOrHighestSeries",
            "latestEraOrHighestErathem",
            "latestPeriodOrHighestSystem",
            "license",
            "lifeStage",
            "lithostratigraphicTerms",
            "locality",
            "locationAccordingTo",
            "locationID",
            "locationRemarks",
            "lowestBiostratigraphicZone",
            "materialEntityID",
            "materialEntityRemarks",
            "materialEntityType",
            "materialSampleID",
            "maximumDepthInMeters",
            "maximumDistanceAboveSurfaceInMeters",
            "maximumElevationInMeters",
            "member",
            "minimumDepthInMeters",
            "minimumDistanceAboveSurfaceInMeters",
            "minimumElevationInMeters",
            "modified",
            "month",
            "municipality",
            "nameAccordingTo",
            "nameAccordingToID",
            "namePublishedIn",
            "namePublishedInID",
            "namePublishedInYear",
            "nomenclaturalCode",
            "nomenclaturalStatus",
            "occurrenceID",
            "occurrenceRemarks",
            "occurrenceStatus",
            "order",
            "organismID",
            "organismName",
            "organismQuantity",
            "organismQuantityType",
            "organismRemarks",
            "organismScope",
            "originalNameUsage",
            "originalNameUsageID",
            "otherCatalogNumbers",
            "ownerInstitutionCode",
            "parentEventID",
            "parentNameUsage",
            "parentNameUsageID",
            "pathway",
            "phylum",
            "pointRadiusSpatialFit",
            "preparations",
            "previousIdentifications",
            "projectID",
            "projectTitle",
            "recordNumber",
            "recordedBy",
            "recordedByID",
            "references",
            "reproductiveCondition",
            "rightsHolder",
            "sampleSizeUnit",
            "sampleSizeValue",
            "samplingEffort",
            "samplingProtocol",
            "scientificName",
            "scientificNameAuthorship",
            "scientificNameID",
            "sex",
            "specificEpithet",
            "startDayOfYear",
            "stateProvince",
            "subfamily",
            "subgenus",
            "subtribe",
            "superfamily",
            "taxonConceptID",
            "taxonID",
            "taxonRank",
            "taxonRemarks",
            "taxonomicStatus",
            "tribe",
            "type",
            "typeStatus",
            "typifiedName",
            "verbatimCoordinateSystem",
            "verbatimCoordinates",
            "verbatimDepth",
            "verbatimElevation",
            "verbatimEventDate",
            "verbatimIdentification",
            "verbatimLabel",
            "verbatimLatitude",
            "verbatimLocality",
            "verbatimLongitude",
            "verbatimSRS",
            "verbatimTaxonRank",
            "vernacularName",
            "verticalDatum",
            "vitality",
            "waterBody",
            "year",
        ),
        id_column="occurrenceID",
    ),
    DarwinCoreCoreType.EVENT: DarwinCoreSchema(
        key="event",
        title="Darwin Core Event",
        spec_uri="https://rs.gbif.org/core/dwc_event_2025-07-10.xml",
        local_filename="cores/dwc_event_2025-07-10.xml",
        row_type="http://rs.tdwg.org/dwc/terms/Event",
        terms=(
            "accessRights",
            "bed",
            "bibliographicCitation",
            "continent",
            "coordinatePrecision",
            "coordinateUncertaintyInMeters",
            "country",
            "countryCode",
            "county",
            "dataGeneralizations",
            "datasetID",
            "datasetName",
            "day",
            "decimalLatitude",
            "decimalLongitude",
            "dynamicProperties",
            "earliestAgeOrLowestStage",
            "earliestEonOrLowestEonothem",
            "earliestEpochOrLowestSeries",
            "earliestEraOrLowestErathem",
            "earliestPeriodOrLowestSystem",
            "endDayOfYear",
            "eventDate",
            "eventID",
            "eventRemarks",
            "eventTime",
            "eventType",
            "fieldNotes",
            "fieldNumber",
            "footprintSRS",
            "footprintSpatialFit",
            "footprintWKT",
            "formation",
            "geodeticDatum",
            "geologicalContextID",
            "georeferenceProtocol",
            "georeferenceRemarks",
            "georeferenceSources",
            "georeferencedBy",
            "georeferencedDate",
            "group",
            "habitat",
            "higherGeography",
            "higherGeographyID",
            "highestBiostratigraphicZone",
            "informationWithheld",
            "institutionCode",
            "institutionID",
            "island",
            "islandGroup",
            "language",
            "latestAgeOrHighestStage",
            "latestEonOrHighestEonothem",
            "latestEpochOrHighestSeries",
            "latestEraOrHighestErathem",
            "latestPeriodOrHighestSystem",
            "license",
            "lithostratigraphicTerms",
            "locality",
            "locationAccordingTo",
            "locationID",
            "locationRemarks",
            "lowestBiostratigraphicZone",
            "maximumDepthInMeters",
            "maximumDistanceAboveSurfaceInMeters",
            "maximumElevationInMeters",
            "member",
            "minimumDepthInMeters",
            "minimumDistanceAboveSurfaceInMeters",
            "minimumElevationInMeters",
            "modified",
            "month",
            "municipality",
            "ownerInstitutionCode",
            "parentEventID",
            "pointRadiusSpatialFit",
            "references",
            "rightsHolder",
            "sampleSizeUnit",
            "sampleSizeValue",
            "samplingEffort",
            "samplingProtocol",
            "startDayOfYear",
            "stateProvince",
            "type",
            "verbatimCoordinateSystem",
            "verbatimCoordinates",
            "verbatimDepth",
            "verbatimElevation",
            "verbatimEventDate",
            "verbatimLatitude",
            "verbatimLocality",
            "verbatimLongitude",
            "verbatimSRS",
            "verticalDatum",
            "waterBody",
            "year",
        ),
        id_column="eventID",
    ),
    DarwinCoreCoreType.TAXON: DarwinCoreSchema(
        key="taxon",
        title="Darwin Core Taxon",
        spec_uri="https://rs.gbif.org/core/dwc_taxon_2025-07-10.xml",
        local_filename="cores/dwc_taxon_2025-07-10.xml",
        row_type="http://rs.tdwg.org/dwc/terms/Taxon",
        terms=(
            "acceptedNameUsage",
            "acceptedNameUsageID",
            "accessRights",
            "bibliographicCitation",
            "class",
            "cultivarEpithet",
            "datasetID",
            "datasetName",
            "family",
            "genericName",
            "genus",
            "higherClassification",
            "informationWithheld",
            "infragenericEpithet",
            "infraspecificEpithet",
            "institutionCode",
            "institutionID",
            "kingdom",
            "language",
            "license",
            "modified",
            "nameAccordingTo",
            "nameAccordingToID",
            "namePublishedIn",
            "namePublishedInID",
            "namePublishedInYear",
            "nomenclaturalCode",
            "nomenclaturalStatus",
            "order",
            "originalNameUsage",
            "originalNameUsageID",
            "parentNameUsage",
            "parentNameUsageID",
            "phylum",
            "references",
            "rightsHolder",
            "scientificName",
            "scientificNameAuthorship",
            "scientificNameID",
            "specificEpithet",
            "subfamily",
            "subgenus",
            "subtribe",
            "superfamily",
            "taxonConceptID",
            "taxonID",
            "taxonRank",
            "taxonRemarks",
            "taxonomicStatus",
            "tribe",
            "verbatimTaxonRank",
            "vernacularName",
        ),
        id_column="taxonID",
    ),
}


EXTENSION_SCHEMAS: Dict[DarwinCoreExtensionType, DarwinCoreSchema] = {
    DarwinCoreExtensionType.MEASUREMENT_OR_FACT: DarwinCoreSchema(
        key="measurements_or_facts_2025-07-10",
        title="Darwin Core Measurement or Facts",
        spec_uri="https://rs.gbif.org/extension/dwc/measurements_or_facts_2025-07-10.xml",
        local_filename="extensions/measurements_or_facts_2025-07-10.xml",
        row_type="http://rs.tdwg.org/dwc/terms/MeasurementOrFact",
        terms=(
            "measurementAccuracy",
            "measurementDeterminedBy",
            "measurementDeterminedDate",
            "measurementID",
            "measurementMethod",
            "measurementRemarks",
            "measurementType",
            "measurementUnit",
            "measurementValue",
            "parentMeasurementID",
            "verbatimMeasurementType",
        ),
        id_column="measurementID",
    ),
    DarwinCoreExtensionType.DNA_DERIVED_DATA: DarwinCoreSchema(
        key="dna_derived_data_2024-07-11",
        title="DNA Derived Data",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/dna_derived_data_2024-07-11.xml",
        local_filename="extensions/dna_derived_data_2024-07-11.xml",
        row_type="http://rs.gbif.org/terms/1.0/DNADerivedData",
        terms=(
            "DNA_sequence",
            "_16s_recover",
            "_16s_recover_software",
            "adapters",
            "ampliconSize",
            "amplificationReactionVolume",
            "amplificationReactionVolumeUnit",
            "annealingTemp",
            "annealingTempUnit",
            "annot",
            "assembly_name",
            "assembly_qual",
            "assembly_software",
            "automaticBaselineValue",
            "automaticThresholdQuantificationCycle",
            "baselineValue",
            "bin_param",
            "bin_software",
            "biotic_relationship",
            "chimera_check",
            "compl_appr",
            "compl_score",
            "compl_software",
            "concentration",
            "concentrationUnit",
            "contam_score",
            "contam_screen_input",
            "contam_screen_param",
            "contaminationAssessment",
            "decontam_software",
            "detec_type",
            "encoded_traits",
            "env_broad_scale",
            "env_local_scale",
            "env_medium",
            "estimatedNumberOfCopies",
            "estimated_size",
            "experimentalVariance",
            "experimental_factor",
            "extrachrom_elements",
            "feat_pred",
            "host_disease_stat",
            "host_pred_appr",
            "host_pred_est_acc",
            "host_spec_range",
            "isol_growth_condt",
            "lib_layout",
            "lib_reads_seqd",
            "lib_screen",
            "lib_size",
            "lib_vector",
            "mag_cov_software",
            "methodDeterminationConcentrationAndRatios",
            "mid",
            "neg_cont_type",
            "nucl_acid_amp",
            "nucl_acid_ext",
            "num_replicons",
            "number_contig",
            "occurrenceID",
            "otu_class_appr",
            "otu_db",
            "otu_seq_comp_appr",
            "partitionVolume",
            "partitionVolumeUnit",
            "pathogenicity",
            "pcr_analysis_software",
            "pcr_cond",
            "pcr_primer_forward",
            "pcr_primer_lod",
            "pcr_primer_loq",
            "pcr_primer_name_forward",
            "pcr_primer_name_reverse",
            "pcr_primer_reference",
            "pcr_primer_reverse",
            "pcr_primers",
            "ploidy",
            "pos_cont_type",
            "pred_genome_struc",
            "pred_genome_type",
            "probeQuencher",
            "probeReporter",
            "project_name",
            "propagation",
            "quantificationCycle",
            "ratioOfAbsorbance260_230",
            "ratioOfAbsorbance260_280",
            "reassembly_bin",
            "ref_biomaterial",
            "ref_db",
            "rel_to_oxygen",
            "samp_collec_device",
            "samp_collec_method",
            "samp_mat_process",
            "samp_name",
            "samp_size",
            "samp_taxon_id",
            "samp_vol_we_dna_ext",
            "seq_meth",
            "seq_quality_check",
            "sim_search_meth",
            "single_cell_lysis_appr",
            "single_cell_lysis_prot",
            "size_frac",
            "sop",
            "sort_tech",
            "source_mat_id",
            "source_uvig",
            "specific_host",
            "subspecf_gen_lin",
            "target_gene",
            "target_subfragment",
            "tax_class",
            "tax_ident",
            "thresholdQuantificationCycle",
            "trna_ext_software",
            "trnas",
            "trophic_level",
            "url",
            "vir_ident_software",
            "virus_enrich_appr",
            "wga_amp_appr",
            "wga_amp_kit",
        ),
    ),
    DarwinCoreExtensionType.IDENTIFICATION: DarwinCoreSchema(
        key="identification",
        title="Darwin Core Identification",
        spec_uri="https://rs.gbif.org/extension/dwc/identification.xml",
        local_filename="extensions/identification.xml",
        row_type="http://rs.tdwg.org/dwc/terms/Identification",
        terms=(
            "acceptedNameUsage",
            "class",
            "dateIdentified",
            "family",
            "genus",
            "higherClassification",
            "identificationID",
            "identificationQualifier",
            "identificationReferences",
            "identificationRemarks",
            "identificationVerificationStatus",
            "identifiedBy",
            "infraspecificEpithet",
            "kingdom",
            "nameAccordingTo",
            "nameAccordingToID",
            "namePublishedIn",
            "namePublishedInID",
            "namePublishedInYear",
            "nomenclaturalCode",
            "nomenclaturalStatus",
            "order",
            "originalNameUsage",
            "parentNameUsage",
            "phylum",
            "scientificName",
            "scientificNameAuthorship",
            "scientificNameID",
            "specificEpithet",
            "subgenus",
            "taxonConceptID",
            "taxonID",
            "taxonRank",
            "taxonRemarks",
            "taxonomicStatus",
            "typeStatus",
            "verbatimTaxonRank",
            "vernacularName",
        ),
        id_column="identificationID",
    ),
    DarwinCoreExtensionType.IDENTIFICATION_HISTORY: DarwinCoreSchema(
        key="identification_history_2025-07-10",
        title="Darwin Core Identification History",
        spec_uri="https://rs.gbif.org/extension/dwc/identification_history_2025-07-10.xml",
        local_filename="extensions/identification_history_2025-07-10.xml",
        row_type="http://rs.tdwg.org/dwc/terms/Identification",
        terms=(
            "acceptedNameUsage",
            "acceptedNameUsageID",
            "class",
            "cultivarEpithet",
            "dateIdentified",
            "family",
            "genericName",
            "genus",
            "higherClassification",
            "identificationID",
            "identificationQualifier",
            "identificationReferences",
            "identificationRemarks",
            "identificationVerificationStatus",
            "identifiedBy",
            "identifiedByID",
            "infragenericEpithet",
            "infraspecificEpithet",
            "kingdom",
            "nameAccordingTo",
            "nameAccordingToID",
            "namePublishedIn",
            "namePublishedInID",
            "namePublishedInYear",
            "nomenclaturalCode",
            "nomenclaturalStatus",
            "order",
            "originalNameUsage",
            "originalNameUsageID",
            "parentNameUsage",
            "parentNameUsageID",
            "phylum",
            "scientificName",
            "scientificNameAuthorship",
            "scientificNameID",
            "specificEpithet",
            "subfamily",
            "subgenus",
            "subtribe",
            "superfamily",
            "taxonConceptID",
            "taxonID",
            "taxonRank",
            "taxonRemarks",
            "taxonomicStatus",
            "tribe",
            "typeStatus",
            "verbatimIdentification",
            "verbatimTaxonRank",
            "vernacularName",
        ),
        id_column="identificationID",
    ),
    DarwinCoreExtensionType.IDENTIFIER: DarwinCoreSchema(
        key="identifier",
        title="Alternative Identifiers",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/identifier.xml",
        local_filename="extensions/identifier.xml",
        row_type="http://rs.gbif.org/terms/1.0/Identifier",
        terms=("datasetID", "format", "identifier", "subject", "title"),
    ),
    DarwinCoreExtensionType.DESCRIPTION: DarwinCoreSchema(
        key="description",
        title="Taxon Description",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/description.xml",
        local_filename="extensions/description.xml",
        row_type="http://rs.gbif.org/terms/1.0/Description",
        terms=(
            "audience",
            "contributor",
            "created",
            "creator",
            "datasetID",
            "description",
            "language",
            "license",
            "rightsHolder",
            "source",
            "type",
        ),
    ),
    DarwinCoreExtensionType.DISTRIBUTION: DarwinCoreSchema(
        key="distribution_2022-02-02",
        title="Species Distribution",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/distribution_2022-02-02.xml",
        local_filename="extensions/distribution_2022-02-02.xml",
        row_type="http://rs.gbif.org/terms/1.0/Distribution",
        terms=(
            "appendixCITES",
            "countryCode",
            "datasetID",
            "degreeOfEstablishment",
            "endDayOfYear",
            "establishmentMeans",
            "eventDate",
            "lifeStage",
            "locality",
            "locationID",
            "occurrenceRemarks",
            "occurrenceStatus",
            "pathway",
            "source",
            "startDayOfYear",
            "threatStatus",
        ),
    ),
    DarwinCoreExtensionType.MULTIMEDIA: DarwinCoreSchema(
        key="multimedia",
        title="Simple Multimedia",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/multimedia.xml",
        local_filename="extensions/multimedia.xml",
        row_type="http://rs.gbif.org/terms/1.0/Multimedia",
        terms=(
            "audience",
            "contributor",
            "created",
            "creator",
            "datasetID",
            "description",
            "format",
            "identifier",
            "license",
            "publisher",
            "references",
            "rightsHolder",
            "source",
            "title",
            "type",
        ),
    ),
    DarwinCoreExtensionType.REFERENCES: DarwinCoreSchema(
        key="references",
        title="Literature References",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/references.xml",
        local_filename="extensions/references.xml",
        row_type="http://rs.gbif.org/terms/1.0/Reference",
        terms=(
            "bibliographicCitation",
            "creator",
            "datasetID",
            "date",
            "description",
            "identifier",
            "language",
            "rights",
            "source",
            "subject",
            "taxonRemarks",
            "title",
            "type",
        ),
    ),
    DarwinCoreExtensionType.RESOURCE_RELATION: DarwinCoreSchema(
        key="resource_relation_2018_01_18",
        title="Darwin Core Resource Relation",
        spec_uri="https://rs.gbif.org/extension/dwc/resource_relation_2018_01_18.xml",
        local_filename="extensions/resource_relation_2018_01_18.xml",
        row_type="http://rs.tdwg.org/dwc/terms/ResourceRelationship",
        terms=(
            "relatedResourceID",
            "relationshipAccordingTo",
            "relationshipEstablishedDate",
            "relationshipOfResource",
            "relationshipRemarks",
            "resourceID",
            "resourceRelationshipID",
        ),
        id_column="resourceRelationshipID",
    ),
    DarwinCoreExtensionType.RESOURCE_RELATIONSHIP: DarwinCoreSchema(
        key="resource_relationship_2025-07-10",
        title="Darwin Core Resource Relationship",
        spec_uri="https://rs.gbif.org/extension/dwc/resource_relationship_2025-07-10.xml",
        local_filename="extensions/resource_relationship_2025-07-10.xml",
        row_type="http://rs.tdwg.org/dwc/terms/ResourceRelationship",
        terms=(
            "relatedResourceID",
            "relationshipAccordingTo",
            "relationshipEstablishedDate",
            "relationshipOfResource",
            "relationshipOfResourceID",
            "relationshipRemarks",
            "resourceID",
            "resourceRelationshipID",
        ),
        id_column="resourceRelationshipID",
    ),
    DarwinCoreExtensionType.SPECIES_PROFILE: DarwinCoreSchema(
        key="speciesprofile_2019-01-29",
        title="Species Profile",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/speciesprofile_2019-01-29.xml",
        local_filename="extensions/speciesprofile_2019-01-29.xml",
        row_type="http://rs.gbif.org/terms/1.0/SpeciesProfile",
        terms=(
            "ageInDays",
            "datasetID",
            "habitat",
            "isExtinct",
            "isFreshwater",
            "isHybrid",
            "isInvasive",
            "isMarine",
            "isTerrestrial",
            "lifeForm",
            "livingPeriod",
            "massInGrams",
            "sex",
            "sizeInMillimeters",
            "source",
        ),
    ),
    DarwinCoreExtensionType.TYPES_AND_SPECIMEN: DarwinCoreSchema(
        key="typesandspecimen",
        title="Types and Specimen",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/typesandspecimen.xml",
        local_filename="extensions/typesandspecimen.xml",
        row_type="http://rs.gbif.org/terms/1.0/TypesAndSpecimen",
        terms=(
            "bibliographicCitation",
            "catalogNumber",
            "collectionCode",
            "datasetID",
            "institutionCode",
            "locality",
            "occurrenceID",
            "recordedBy",
            "scientificName",
            "sex",
            "source",
            "taxonRank",
            "typeDesignatedBy",
            "typeDesignationType",
            "typeStatus",
            "verbatimEventDate",
            "verbatimLabel",
            "verbatimLatitude",
            "verbatimLongitude",
        ),
    ),
    DarwinCoreExtensionType.VERNACULAR_NAME: DarwinCoreSchema(
        key="vernacularname",
        title="Vernacular Name",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/vernacularname.xml",
        local_filename="extensions/vernacularname.xml",
        row_type="http://rs.gbif.org/terms/1.0/VernacularName",
        terms=(
            "countryCode",
            "datasetID",
            "isPlural",
            "isPreferredName",
            "language",
            "lifeStage",
            "locality",
            "locationID",
            "organismPart",
            "sex",
            "source",
            "taxonRemarks",
            "temporal",
            "vernacularName",
        ),
    ),
    DarwinCoreExtensionType.RELEVE: DarwinCoreSchema(
        key="releve_2016-05-10",
        title="Relevé",
        spec_uri=None,
        local_filename="extensions/releve_2016-05-10.xml",
        row_type="http://rs.gbif.org/terms/1.0/Releve",
        terms=(
            "aspect",
            "coverAlgaeInPercentage",
            "coverCryptogamsInPercentage",
            "coverHerbsInPercentage",
            "coverLichensInPercentage",
            "coverLitterInPercentage",
            "coverMossesInPercentage",
            "coverRockInPercentage",
            "coverShrubsInPercentage",
            "coverTotalInPercentage",
            "coverTreesInPercentage",
            "coverWaterInPercentage",
            "herbLayerHeightInCentimeters",
            "inclinationInDegrees",
            "lichensIdentified",
            "mossesIdentified",
            "project",
            "shrubLayerHeightInMeters",
            "syntaxonName",
            "treeLayerHeightInMeters",
        ),
    ),
    DarwinCoreExtensionType.CHRONOMETRIC_AGE: DarwinCoreSchema(
        key="ChronometricAge_2024-03-11",
        title="Chronometric Age",
        spec_uri=None,
        local_filename="extensions/ChronometricAge_2024-03-11.xml",
        row_type="http://rs.tdwg.org/chrono/terms/ChronometricAge",
        terms=(
            "chronometricAgeConversionProtocol",
            "chronometricAgeDeterminedBy",
            "chronometricAgeDeterminedDate",
            "chronometricAgeID",
            "chronometricAgeProtocol",
            "chronometricAgeReferences",
            "chronometricAgeRemarks",
            "chronometricAgeUncertaintyInYears",
            "chronometricAgeUncertaintyMethod",
            "earliestChronometricAge",
            "earliestChronometricAgeReferenceSystem",
            "latestChronometricAge",
            "latestChronometricAgeReferenceSystem",
            "materialDated",
            "materialDatedID",
            "materialDatedRelationship",
            "uncalibratedChronometricAge",
            "verbatimChronometricAge",
        ),
        id_column="chronometricAgeID",
    ),
}


ALL_SCHEMAS: Tuple[DarwinCoreSchema, ...] = tuple(CORE_SCHEMAS.values()) + tuple(
    EXTENSION_SCHEMAS.values()
)


def iter_schemas(include_extensions: bool = True) -> Iterable[DarwinCoreSchema]:
    yield from CORE_SCHEMAS.values()
    if include_extensions:
        yield from EXTENSION_SCHEMAS.values()


