from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Dict, Iterable, Tuple


_BASE_DIR = Path(__file__).resolve().parent
_TEMPLATES_ROOT = _BASE_DIR / "templates"


@dataclass(frozen=True)
class DarwinCoreSchema:
    key: str
    title: str
    spec_uri: str | None
    local_filename: str
    row_type: str
    terms: Tuple[str, ...]
    core_id_column: str | None = None
    compatible_cores: Tuple[str, ...] = ()
    subject: str = ""
    typical_dwc_dp_resources: Tuple[str, ...] = ()
    use_when: str = ""
    avoid_when: str = ""

    @property
    def spec_path(self) -> str:
        local_path = (_TEMPLATES_ROOT / self.local_filename).resolve()
        if not local_path.exists():
            message = (
                f"Local Darwin Core schema not found at {local_path}. "
                "Each schema should be vendored into the repository under api/templates."
            )
            if self.spec_uri:
                message += f" Remote reference: {self.spec_uri}"
            raise FileNotFoundError(message)
        return str(local_path)

    @property
    def remote_spec_uri(self) -> str | None:
        return self.spec_uri

    @property
    def normalized_terms(self) -> set[str]:
        return {term.lower() for term in self.terms}


class DarwinCoreCoreType(str, Enum):
    OCCURRENCE = "occurrence"
    EVENT = "event"
    TAXON = "taxon"

    def __str__(self) -> str:
        return self.value


class DarwinCoreExtensionType(str, Enum):
    OCCURRENCE = "occurrence"
    HUMBOLDT_ECOLOGICAL_INVENTORY = "humboldt_ecological_inventory"
    MEASUREMENT_OR_FACT = "measurement_or_fact"
    DNA_DERIVED_DATA = "dna_derived_data"
    IDENTIFICATION = "identification"
    IDENTIFICATION_HISTORY = "identification_history"
    IDENTIFIER = "identifier"
    DESCRIPTION = "description"
    DISTRIBUTION = "distribution"
    MULTIMEDIA = "multimedia"
    REFERENCES = "references"
    RESOURCE_RELATION = "resource_relation"
    RESOURCE_RELATIONSHIP = "resource_relationship"
    SPECIES_PROFILE = "species_profile"
    TYPES_AND_SPECIMEN = "types_and_specimen"
    VERNACULAR_NAME = "vernacular_name"
    RELEVE = "releve"
    CHRONOMETRIC_AGE = "chronometric_age"

    def __str__(self) -> str:
        return self.value


CORE_SCHEMAS: Dict[DarwinCoreCoreType, DarwinCoreSchema] = {
    DarwinCoreCoreType.OCCURRENCE: DarwinCoreSchema(
        key="occurrence",
        title="Darwin Core Occurrence",
        spec_uri="https://rs.gbif.org/core/dwc_occurrence_2025-07-10.xml",
        local_filename="cores/dwc_occurrence_2025-07-10.xml",
        row_type="http://rs.tdwg.org/dwc/terms/Occurrence",
        terms=(
            "acceptedNameUsage",
            "acceptedNameUsageID",
            "accessRights",
            "associatedMedia",
            "associatedOccurrences",
            "associatedOrganisms",
            "associatedReferences",
            "associatedSequences",
            "associatedTaxa",
            "basisOfRecord",
            "bed",
            "behavior",
            "bibliographicCitation",
            "caste",
            "catalogNumber",
            "causeOfDeath",
            "class",
            "collectionCode",
            "collectionID",
            "continent",
            "coordinatePrecision",
            "coordinateUncertaintyInMeters",
            "country",
            "countryCode",
            "county",
            "cultivarEpithet",
            "dataGeneralizations",
            "datasetID",
            "datasetName",
            "dateIdentified",
            "day",
            "decimalLatitude",
            "decimalLongitude",
            "degreeOfEstablishment",
            "digitalSpecimenID",
            "discipline",
            "disposition",
            "dynamicProperties",
            "earliestAgeOrLowestStage",
            "earliestEonOrLowestEonothem",
            "earliestEpochOrLowestSeries",
            "earliestEraOrLowestErathem",
            "earliestPeriodOrLowestSystem",
            "endDayOfYear",
            "establishmentMeans",
            "eventDate",
            "eventID",
            "eventRemarks",
            "eventTime",
            "eventType",
            "family",
            "feedbackURL",
            "fieldNotes",
            "fieldNumber",
            "footprintSRS",
            "footprintSpatialFit",
            "footprintWKT",
            "formation",
            "fundingAttribution",
            "fundingAttributionID",
            "genericName",
            "genus",
            "geodeticDatum",
            "geologicalContextID",
            "georeferenceProtocol",
            "georeferenceRemarks",
            "georeferenceSources",
            "georeferenceVerificationStatus",
            "georeferencedBy",
            "georeferencedDate",
            "group",
            "habitat",
            "higherClassification",
            "higherGeography",
            "higherGeographyID",
            "highestBiostratigraphicZone",
            "identificationID",
            "identificationQualifier",
            "identificationReferences",
            "identificationRemarks",
            "identificationVerificationStatus",
            "identifiedBy",
            "identifiedByID",
            "individualCount",
            "informationWithheld",
            "infragenericEpithet",
            "infraspecificEpithet",
            "institutionCode",
            "institutionID",
            "island",
            "islandGroup",
            "kingdom",
            "language",
            "latestAgeOrHighestStage",
            "latestEonOrHighestEonothem",
            "latestEpochOrHighestSeries",
            "latestEraOrHighestErathem",
            "latestPeriodOrHighestSystem",
            "license",
            "lifeStage",
            "lithostratigraphicTerms",
            "locality",
            "locationAccordingTo",
            "locationID",
            "locationRemarks",
            "lowestBiostratigraphicZone",
            "materialEntityID",
            "materialEntityRemarks",
            "materialEntityType",
            "materialSampleID",
            "maximumDepthInMeters",
            "maximumDistanceAboveSurfaceInMeters",
            "maximumElevationInMeters",
            "member",
            "minimumDepthInMeters",
            "minimumDistanceAboveSurfaceInMeters",
            "minimumElevationInMeters",
            "modified",
            "month",
            "municipality",
            "nameAccordingTo",
            "nameAccordingToID",
            "namePublishedIn",
            "namePublishedInID",
            "namePublishedInYear",
            "nomenclaturalCode",
            "nomenclaturalStatus",
            "occurrenceID",
            "occurrenceRemarks",
            "occurrenceStatus",
            "order",
            "organismID",
            "organismName",
            "organismQuantity",
            "organismQuantityType",
            "organismRemarks",
            "organismScope",
            "originalNameUsage",
            "originalNameUsageID",
            "otherCatalogNumbers",
            "ownerInstitutionCode",
            "parentEventID",
            "parentNameUsage",
            "parentNameUsageID",
            "pathway",
            "phylum",
            "pointRadiusSpatialFit",
            "preparations",
            "previousIdentifications",
            "projectID",
            "projectTitle",
            "recordNumber",
            "recordedBy",
            "recordedByID",
            "references",
            "reproductiveCondition",
            "rightsHolder",
            "sampleSizeUnit",
            "sampleSizeValue",
            "samplingEffort",
            "samplingProtocol",
            "scientificName",
            "scientificNameAuthorship",
            "scientificNameID",
            "sex",
            "specificEpithet",
            "startDayOfYear",
            "stateProvince",
            "subfamily",
            "subgenus",
            "subtribe",
            "superfamily",
            "taxonConceptID",
            "taxonID",
            "taxonRank",
            "taxonRemarks",
            "taxonomicStatus",
            "tribe",
            "type",
            "typeStatus",
            "typifiedName",
            "verbatimCoordinateSystem",
            "verbatimCoordinates",
            "verbatimDepth",
            "verbatimElevation",
            "verbatimEventDate",
            "verbatimIdentification",
            "verbatimLabel",
            "verbatimLatitude",
            "verbatimLocality",
            "verbatimLongitude",
            "verbatimSRS",
            "verbatimTaxonRank",
            "vernacularName",
            "verticalDatum",
            "vitality",
            "waterBody",
            "year",
        ),
        core_id_column="occurrenceID",
    ),
    DarwinCoreCoreType.EVENT: DarwinCoreSchema(
        key="event",
        title="Darwin Core Event",
        spec_uri="https://rs.gbif.org/core/dwc_event_2025-07-10.xml",
        local_filename="cores/dwc_event_2025-07-10.xml",
        row_type="http://rs.tdwg.org/dwc/terms/Event",
        terms=(
            "accessRights",
            "bed",
            "bibliographicCitation",
            "continent",
            "coordinatePrecision",
            "coordinateUncertaintyInMeters",
            "country",
            "countryCode",
            "county",
            "dataGeneralizations",
            "datasetID",
            "datasetName",
            "day",
            "decimalLatitude",
            "decimalLongitude",
            "dynamicProperties",
            "earliestAgeOrLowestStage",
            "earliestEonOrLowestEonothem",
            "earliestEpochOrLowestSeries",
            "earliestEraOrLowestErathem",
            "earliestPeriodOrLowestSystem",
            "endDayOfYear",
            "eventDate",
            "eventID",
            "eventRemarks",
            "eventTime",
            "eventType",
            "fieldNotes",
            "fieldNumber",
            "footprintSRS",
            "footprintSpatialFit",
            "footprintWKT",
            "formation",
            "geodeticDatum",
            "geologicalContextID",
            "georeferenceProtocol",
            "georeferenceRemarks",
            "georeferenceSources",
            "georeferencedBy",
            "georeferencedDate",
            "group",
            "habitat",
            "higherGeography",
            "higherGeographyID",
            "highestBiostratigraphicZone",
            "informationWithheld",
            "institutionCode",
            "institutionID",
            "island",
            "islandGroup",
            "language",
            "latestAgeOrHighestStage",
            "latestEonOrHighestEonothem",
            "latestEpochOrHighestSeries",
            "latestEraOrHighestErathem",
            "latestPeriodOrHighestSystem",
            "license",
            "lithostratigraphicTerms",
            "locality",
            "locationAccordingTo",
            "locationID",
            "locationRemarks",
            "lowestBiostratigraphicZone",
            "maximumDepthInMeters",
            "maximumDistanceAboveSurfaceInMeters",
            "maximumElevationInMeters",
            "member",
            "minimumDepthInMeters",
            "minimumDistanceAboveSurfaceInMeters",
            "minimumElevationInMeters",
            "modified",
            "month",
            "municipality",
            "ownerInstitutionCode",
            "parentEventID",
            "pointRadiusSpatialFit",
            "references",
            "rightsHolder",
            "sampleSizeUnit",
            "sampleSizeValue",
            "samplingEffort",
            "samplingProtocol",
            "startDayOfYear",
            "stateProvince",
            "type",
            "verbatimCoordinateSystem",
            "verbatimCoordinates",
            "verbatimDepth",
            "verbatimElevation",
            "verbatimEventDate",
            "verbatimLatitude",
            "verbatimLocality",
            "verbatimLongitude",
            "verbatimSRS",
            "verticalDatum",
            "waterBody",
            "year",
        ),
        core_id_column="eventID",
    ),
    DarwinCoreCoreType.TAXON: DarwinCoreSchema(
        key="taxon",
        title="Darwin Core Taxon",
        spec_uri="https://rs.gbif.org/core/dwc_taxon_2025-07-10.xml",
        local_filename="cores/dwc_taxon_2025-07-10.xml",
        row_type="http://rs.tdwg.org/dwc/terms/Taxon",
        terms=(
            "acceptedNameUsage",
            "acceptedNameUsageID",
            "accessRights",
            "bibliographicCitation",
            "class",
            "cultivarEpithet",
            "datasetID",
            "datasetName",
            "family",
            "genericName",
            "genus",
            "higherClassification",
            "informationWithheld",
            "infragenericEpithet",
            "infraspecificEpithet",
            "institutionCode",
            "institutionID",
            "kingdom",
            "language",
            "license",
            "modified",
            "nameAccordingTo",
            "nameAccordingToID",
            "namePublishedIn",
            "namePublishedInID",
            "namePublishedInYear",
            "nomenclaturalCode",
            "nomenclaturalStatus",
            "order",
            "originalNameUsage",
            "originalNameUsageID",
            "parentNameUsage",
            "parentNameUsageID",
            "phylum",
            "references",
            "rightsHolder",
            "scientificName",
            "scientificNameAuthorship",
            "scientificNameID",
            "specificEpithet",
            "subfamily",
            "subgenus",
            "subtribe",
            "superfamily",
            "taxonConceptID",
            "taxonID",
            "taxonRank",
            "taxonRemarks",
            "taxonomicStatus",
            "tribe",
            "verbatimTaxonRank",
            "vernacularName",
        ),
        core_id_column="taxonID",
    ),
}


EXTENSION_SCHEMAS: Dict[DarwinCoreExtensionType, DarwinCoreSchema] = {
    DarwinCoreExtensionType.OCCURRENCE: DarwinCoreSchema(
        key="dwc_occurrence_2025-07-10",
        title="Darwin Core Occurrence",
        spec_uri="https://rs.gbif.org/core/dwc_occurrence_2025-07-10.xml",
        local_filename="cores/dwc_occurrence_2025-07-10.xml",
        row_type="http://rs.tdwg.org/dwc/terms/Occurrence",
        terms=CORE_SCHEMAS[DarwinCoreCoreType.OCCURRENCE].terms,
        compatible_cores=("event", "taxon"),
        subject="An organism occurrence linked to a focal Event or Taxon core record.",
        typical_dwc_dp_resources=("occurrence",),
        use_when=(
            "The chosen core is Event or Taxon and the package contains meaningful occurrence "
            "records that can be linked unambiguously to it."
        ),
        avoid_when="Occurrence is already the core, or rows cannot resolve to one core record.",
    ),
    DarwinCoreExtensionType.HUMBOLDT_ECOLOGICAL_INVENTORY: DarwinCoreSchema(
        key="humboldt_2025-07-10",
        title="Humboldt Ecological Inventory",
        spec_uri="https://rs.gbif.org/extension/eco/humboldt_2025-07-10.xml",
        local_filename="extensions/humboldt_2025-07-10.xml",
        row_type="http://rs.tdwg.org/eco/terms/Event",
        terms=(
            "siteCount",
            "siteNestingDescription",
            "verbatimSiteDescriptions",
            "verbatimSiteNames",
            "geospatialScopeAreaValue",
            "geospatialScopeAreaUnit",
            "totalAreaSampledValue",
            "totalAreaSampledUnit",
            "reportedWeather",
            "reportedExtremeConditions",
            "targetHabitatScope",
            "excludedHabitatScope",
            "eventDurationValue",
            "eventDurationUnit",
            "targetTaxonomicScope",
            "excludedTaxonomicScope",
            "taxonCompletenessReported",
            "taxonCompletenessProtocols",
            "isTaxonomicScopeFullyReported",
            "isAbsenceReported",
            "absentTaxa",
            "hasNonTargetTaxa",
            "nonTargetTaxa",
            "areNonTargetTaxaFullyReported",
            "targetLifeStageScope",
            "excludedLifeStageScope",
            "isLifeStageScopeFullyReported",
            "targetDegreeOfEstablishmentScope",
            "excludedDegreeOfEstablishmentScope",
            "isDegreeOfEstablishmentScopeFullyReported",
            "targetGrowthFormScope",
            "excludedGrowthFormScope",
            "isGrowthFormScopeFullyReported",
            "hasNonTargetOrganisms",
            "verbatimTargetScope",
            "identifiedBy",
            "identificationReferences",
            "compilationTypes",
            "compilationSourceTypes",
            "inventoryTypes",
            "protocolNames",
            "protocolDescriptions",
            "protocolReferences",
            "isAbundanceReported",
            "isAbundanceCapReported",
            "abundanceCap",
            "isVegetationCoverReported",
            "isLeastSpecificTargetCategoryQuantityInclusive",
            "hasVouchers",
            "voucherInstitutions",
            "hasMaterialSamples",
            "materialSampleTypes",
            "samplingPerformedBy",
            "isSamplingEffortReported",
            "samplingEffortProtocol",
            "samplingEffortValue",
            "samplingEffortUnit",
        ),
        compatible_cores=("event",),
        subject="Survey design, scope, methods, effort, and completeness for a Darwin Core Event.",
        typical_dwc_dp_resources=("survey",),
        use_when=(
            "The Event-centred package explicitly reports inventory or survey design, scope, "
            "protocol, effort, completeness, abundance, or non-detection context."
        ),
        avoid_when=(
            "The data merely contain field occurrences, the chosen core is not Event, or survey "
            "properties would have to be inferred from detected occurrences."
        ),
    ),
    DarwinCoreExtensionType.MEASUREMENT_OR_FACT: DarwinCoreSchema(
        key="measurements_or_facts_2025-07-10",
        title="Darwin Core Measurement or Facts",
        spec_uri="https://rs.gbif.org/extension/dwc/measurements_or_facts_2025-07-10.xml",
        local_filename="extensions/measurements_or_facts_2025-07-10.xml",
        row_type="http://rs.tdwg.org/dwc/terms/MeasurementOrFact",
        terms=(
            "measurementAccuracy",
            "measurementDeterminedBy",
            "measurementDeterminedDate",
            "measurementID",
            "measurementMethod",
            "measurementRemarks",
            "measurementType",
            "measurementUnit",
            "measurementValue",
            "parentMeasurementID",
            "verbatimMeasurementType",
        ),
        compatible_cores=("occurrence", "event", "taxon"),
        subject="A repeatable measurement or fact about a core record.",
        typical_dwc_dp_resources=(
            "occurrence-assertion",
            "event-assertion",
            "survey-assertion",
            "material-assertion",
        ),
        use_when="Repeated or qualified measurements or facts map exactly to registered terms.",
        avoid_when="A native core term expresses the fact without losing meaning.",
    ),
    DarwinCoreExtensionType.DNA_DERIVED_DATA: DarwinCoreSchema(
        key="dna_derived_data_2024-07-11",
        title="DNA Derived Data",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/dna_derived_data_2024-07-11.xml",
        local_filename="extensions/dna_derived_data_2024-07-11.xml",
        row_type="http://rs.gbif.org/terms/1.0/DNADerivedData",
        terms=(
            "DNA_sequence",
            "_16s_recover",
            "_16s_recover_software",
            "adapters",
            "ampliconSize",
            "amplificationReactionVolume",
            "amplificationReactionVolumeUnit",
            "annealingTemp",
            "annealingTempUnit",
            "annot",
            "assembly_name",
            "assembly_qual",
            "assembly_software",
            "automaticBaselineValue",
            "automaticThresholdQuantificationCycle",
            "baselineValue",
            "bin_param",
            "bin_software",
            "biotic_relationship",
            "chimera_check",
            "compl_appr",
            "compl_score",
            "compl_software",
            "concentration",
            "concentrationUnit",
            "contam_score",
            "contam_screen_input",
            "contam_screen_param",
            "contaminationAssessment",
            "decontam_software",
            "detec_type",
            "encoded_traits",
            "env_broad_scale",
            "env_local_scale",
            "env_medium",
            "estimatedNumberOfCopies",
            "estimated_size",
            "experimentalVariance",
            "experimental_factor",
            "extrachrom_elements",
            "feat_pred",
            "host_disease_stat",
            "host_pred_appr",
            "host_pred_est_acc",
            "host_spec_range",
            "isol_growth_condt",
            "lib_layout",
            "lib_reads_seqd",
            "lib_screen",
            "lib_size",
            "lib_vector",
            "mag_cov_software",
            "methodDeterminationConcentrationAndRatios",
            "mid",
            "neg_cont_type",
            "nucl_acid_amp",
            "nucl_acid_ext",
            "num_replicons",
            "number_contig",
            "occurrenceID",
            "otu_class_appr",
            "otu_db",
            "otu_seq_comp_appr",
            "partitionVolume",
            "partitionVolumeUnit",
            "pathogenicity",
            "pcr_analysis_software",
            "pcr_cond",
            "pcr_primer_forward",
            "pcr_primer_lod",
            "pcr_primer_loq",
            "pcr_primer_name_forward",
            "pcr_primer_name_reverse",
            "pcr_primer_reference",
            "pcr_primer_reverse",
            "pcr_primers",
            "ploidy",
            "pos_cont_type",
            "pred_genome_struc",
            "pred_genome_type",
            "probeQuencher",
            "probeReporter",
            "project_name",
            "propagation",
            "quantificationCycle",
            "ratioOfAbsorbance260_230",
            "ratioOfAbsorbance260_280",
            "reassembly_bin",
            "ref_biomaterial",
            "ref_db",
            "rel_to_oxygen",
            "samp_collec_device",
            "samp_collec_method",
            "samp_mat_process",
            "samp_name",
            "samp_size",
            "samp_taxon_id",
            "samp_vol_we_dna_ext",
            "seq_meth",
            "seq_quality_check",
            "sim_search_meth",
            "single_cell_lysis_appr",
            "single_cell_lysis_prot",
            "size_frac",
            "sop",
            "sort_tech",
            "source_mat_id",
            "source_uvig",
            "specific_host",
            "subspecf_gen_lin",
            "target_gene",
            "target_subfragment",
            "tax_class",
            "tax_ident",
            "thresholdQuantificationCycle",
            "trna_ext_software",
            "trnas",
            "trophic_level",
            "url",
            "vir_ident_software",
            "virus_enrich_appr",
            "wga_amp_appr",
            "wga_amp_kit",
        ),
        compatible_cores=("occurrence", "event"),
        subject="DNA sequences, assays, and laboratory or bioinformatics methods for an occurrence or event.",
        typical_dwc_dp_resources=("nucleotide-analysis", "nucleotide-sequence", "molecular-protocol"),
        use_when="Explicit molecular data or methods can be linked to an Occurrence or Event core record.",
        avoid_when="The package has no molecular evidence, or rows cannot resolve to a core record.",
    ),
    DarwinCoreExtensionType.IDENTIFICATION: DarwinCoreSchema(
        key="identification",
        title="Darwin Core Identification",
        spec_uri="https://rs.gbif.org/extension/dwc/identification.xml",
        local_filename="extensions/identification.xml",
        row_type="http://rs.tdwg.org/dwc/terms/Identification",
        terms=(
            "acceptedNameUsage",
            "class",
            "dateIdentified",
            "family",
            "genus",
            "higherClassification",
            "identificationID",
            "identificationQualifier",
            "identificationReferences",
            "identificationRemarks",
            "identificationVerificationStatus",
            "identifiedBy",
            "infraspecificEpithet",
            "kingdom",
            "nameAccordingTo",
            "nameAccordingToID",
            "namePublishedIn",
            "namePublishedInID",
            "namePublishedInYear",
            "nomenclaturalCode",
            "nomenclaturalStatus",
            "order",
            "originalNameUsage",
            "parentNameUsage",
            "phylum",
            "scientificName",
            "scientificNameAuthorship",
            "scientificNameID",
            "specificEpithet",
            "subgenus",
            "taxonConceptID",
            "taxonID",
            "taxonRank",
            "taxonRemarks",
            "taxonomicStatus",
            "typeStatus",
            "verbatimTaxonRank",
            "vernacularName",
        ),
        compatible_cores=("occurrence",),
        subject="A taxonomic identification or determination of an occurrence.",
        typical_dwc_dp_resources=("identification",),
        use_when="Multiple or detailed determinations are explicitly recorded for an occurrence.",
        avoid_when="Only the current identification represented in the Occurrence core is available.",
    ),
    DarwinCoreExtensionType.IDENTIFICATION_HISTORY: DarwinCoreSchema(
        key="identification_history_2025-07-10",
        title="Darwin Core Identification History",
        spec_uri="https://rs.gbif.org/extension/dwc/identification_history_2025-07-10.xml",
        local_filename="extensions/identification_history_2025-07-10.xml",
        row_type="http://rs.tdwg.org/dwc/terms/Identification",
        terms=(
            "acceptedNameUsage",
            "acceptedNameUsageID",
            "class",
            "cultivarEpithet",
            "dateIdentified",
            "family",
            "genericName",
            "genus",
            "higherClassification",
            "identificationID",
            "identificationQualifier",
            "identificationReferences",
            "identificationRemarks",
            "identificationVerificationStatus",
            "identifiedBy",
            "identifiedByID",
            "infragenericEpithet",
            "infraspecificEpithet",
            "kingdom",
            "nameAccordingTo",
            "nameAccordingToID",
            "namePublishedIn",
            "namePublishedInID",
            "namePublishedInYear",
            "nomenclaturalCode",
            "nomenclaturalStatus",
            "order",
            "originalNameUsage",
            "originalNameUsageID",
            "parentNameUsage",
            "parentNameUsageID",
            "phylum",
            "scientificName",
            "scientificNameAuthorship",
            "scientificNameID",
            "specificEpithet",
            "subfamily",
            "subgenus",
            "subtribe",
            "superfamily",
            "taxonConceptID",
            "taxonID",
            "taxonRank",
            "taxonRemarks",
            "taxonomicStatus",
            "tribe",
            "typeStatus",
            "verbatimIdentification",
            "verbatimTaxonRank",
            "vernacularName",
        ),
        compatible_cores=("occurrence",),
        subject="The history of taxonomic identifications for an occurrence.",
        typical_dwc_dp_resources=("identification",),
        use_when="One occurrence has multiple dated, attributed, or qualified determinations.",
        avoid_when="There is no identification history beyond the current core values.",
    ),
    DarwinCoreExtensionType.IDENTIFIER: DarwinCoreSchema(
        key="identifier",
        title="Alternative Identifiers",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/identifier.xml",
        local_filename="extensions/identifier.xml",
        row_type="http://rs.gbif.org/terms/1.0/Identifier",
        terms=("datasetID", "format", "identifier", "subject", "title"),
        compatible_cores=("occurrence", "event", "taxon"),
        subject="An alternative identifier for a core record.",
        typical_dwc_dp_resources=("identifier",),
        use_when="A core record has an additional meaningful, typed identifier.",
        avoid_when="The row would only repeat the core identifier.",
    ),
    DarwinCoreExtensionType.DESCRIPTION: DarwinCoreSchema(
        key="description",
        title="Taxon Description",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/description.xml",
        local_filename="extensions/description.xml",
        row_type="http://rs.gbif.org/terms/1.0/Description",
        terms=(
            "audience",
            "contributor",
            "created",
            "creator",
            "datasetID",
            "description",
            "language",
            "license",
            "rightsHolder",
            "source",
            "type",
        ),
        compatible_cores=("taxon",),
        subject="A narrative description of a taxon.",
        typical_dwc_dp_resources=("taxon-description",),
        use_when="Taxon records have attributed descriptive text suitable for species pages.",
        avoid_when="The description is structured trait data or the core is not Taxon.",
    ),
    DarwinCoreExtensionType.DISTRIBUTION: DarwinCoreSchema(
        key="distribution_2022-02-02",
        title="Species Distribution",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/distribution_2022-02-02.xml",
        local_filename="extensions/distribution_2022-02-02.xml",
        row_type="http://rs.gbif.org/terms/1.0/Distribution",
        terms=(
            "appendixCITES",
            "countryCode",
            "datasetID",
            "degreeOfEstablishment",
            "endDayOfYear",
            "establishmentMeans",
            "eventDate",
            "lifeStage",
            "locality",
            "locationID",
            "occurrenceRemarks",
            "occurrenceStatus",
            "pathway",
            "source",
            "startDayOfYear",
            "threatStatus",
        ),
        compatible_cores=("taxon",),
        subject="A geographic distribution assertion about a taxon.",
        typical_dwc_dp_resources=("taxon",),
        use_when="A checklist explicitly states taxon presence, absence, or status in an area.",
        avoid_when="The data describe individual observations rather than taxon distribution.",
    ),
    DarwinCoreExtensionType.MULTIMEDIA: DarwinCoreSchema(
        key="multimedia",
        title="Simple Multimedia",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/multimedia.xml",
        local_filename="extensions/multimedia.xml",
        row_type="http://rs.gbif.org/terms/1.0/Multimedia",
        terms=(
            "audience",
            "contributor",
            "created",
            "creator",
            "datasetID",
            "description",
            "format",
            "identifier",
            "license",
            "publisher",
            "references",
            "rightsHolder",
            "source",
            "title",
            "type",
        ),
        compatible_cores=("occurrence", "event", "taxon"),
        subject="Image, audio, video, or other media associated with a core record.",
        typical_dwc_dp_resources=("media",),
        use_when="A resolvable media resource has meaningful metadata and a core-record link.",
        avoid_when="There is no media identifier or the resource cannot be linked to the core.",
    ),
    DarwinCoreExtensionType.REFERENCES: DarwinCoreSchema(
        key="references",
        title="Literature References",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/references.xml",
        local_filename="extensions/references.xml",
        row_type="http://rs.gbif.org/terms/1.0/Reference",
        terms=(
            "bibliographicCitation",
            "creator",
            "datasetID",
            "date",
            "description",
            "identifier",
            "language",
            "rights",
            "source",
            "subject",
            "taxonRemarks",
            "title",
            "type",
        ),
        compatible_cores=("occurrence", "event", "taxon"),
        subject="A literature reference associated with a core record.",
        typical_dwc_dp_resources=("reference",),
        use_when="The source supplies a distinct bibliographic record linked to the core.",
        avoid_when="A single core references or bibliographicCitation value is sufficient.",
    ),
    DarwinCoreExtensionType.RESOURCE_RELATION: DarwinCoreSchema(
        key="resource_relation_2018_01_18",
        title="Darwin Core Resource Relation",
        spec_uri="https://rs.gbif.org/extension/dwc/resource_relation_2018_01_18.xml",
        local_filename="extensions/resource_relation_2018_01_18.xml",
        row_type="http://rs.tdwg.org/dwc/terms/ResourceRelationship",
        terms=(
            "relatedResourceID",
            "relationshipAccordingTo",
            "relationshipEstablishedDate",
            "relationshipOfResource",
            "relationshipRemarks",
            "resourceID",
            "resourceRelationshipID",
        ),
        compatible_cores=("occurrence", "event", "taxon"),
        subject="A typed relationship between the core record and another resource.",
        typical_dwc_dp_resources=("relationship",),
        use_when="An explicit, meaningful resource relationship is present.",
        avoid_when="Either endpoint or the relationship type would need to be invented.",
    ),
    DarwinCoreExtensionType.RESOURCE_RELATIONSHIP: DarwinCoreSchema(
        key="resource_relationship_2025-07-10",
        title="Darwin Core Resource Relationship",
        spec_uri="https://rs.gbif.org/extension/dwc/resource_relationship_2025-07-10.xml",
        local_filename="extensions/resource_relationship_2025-07-10.xml",
        row_type="http://rs.tdwg.org/dwc/terms/ResourceRelationship",
        terms=(
            "relatedResourceID",
            "relationshipAccordingTo",
            "relationshipEstablishedDate",
            "relationshipOfResource",
            "relationshipOfResourceID",
            "relationshipRemarks",
            "resourceID",
            "resourceRelationshipID",
        ),
        compatible_cores=("occurrence", "event", "taxon"),
        subject="A typed relationship between the core record and another resource.",
        typical_dwc_dp_resources=("relationship",),
        use_when="An explicit, meaningful resource relationship is present.",
        avoid_when="Either endpoint or the relationship type would need to be invented.",
    ),
    DarwinCoreExtensionType.SPECIES_PROFILE: DarwinCoreSchema(
        key="speciesprofile_2019-01-29",
        title="Species Profile",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/speciesprofile_2019-01-29.xml",
        local_filename="extensions/speciesprofile_2019-01-29.xml",
        row_type="http://rs.gbif.org/terms/1.0/SpeciesProfile",
        terms=(
            "ageInDays",
            "datasetID",
            "habitat",
            "isExtinct",
            "isFreshwater",
            "isHybrid",
            "isInvasive",
            "isMarine",
            "isTerrestrial",
            "lifeForm",
            "livingPeriod",
            "massInGrams",
            "sex",
            "sizeInMillimeters",
            "source",
        ),
        compatible_cores=("taxon",),
        subject="Structured biological or ecological characteristics of a taxon.",
        typical_dwc_dp_resources=("taxon",),
        use_when="A Taxon package explicitly reports one or more registered profile properties.",
        avoid_when="The values are observations of individuals rather than taxon-level traits.",
    ),
    DarwinCoreExtensionType.TYPES_AND_SPECIMEN: DarwinCoreSchema(
        key="typesandspecimen",
        title="Types and Specimen",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/typesandspecimen.xml",
        local_filename="extensions/typesandspecimen.xml",
        row_type="http://rs.gbif.org/terms/1.0/TypesAndSpecimen",
        terms=(
            "bibliographicCitation",
            "catalogNumber",
            "collectionCode",
            "datasetID",
            "institutionCode",
            "locality",
            "occurrenceID",
            "recordedBy",
            "scientificName",
            "sex",
            "source",
            "taxonRank",
            "typeDesignatedBy",
            "typeDesignationType",
            "typeStatus",
            "verbatimEventDate",
            "verbatimLabel",
            "verbatimLatitude",
            "verbatimLongitude",
        ),
        compatible_cores=("taxon",),
        subject="Type designations and specimens associated with a taxon name.",
        typical_dwc_dp_resources=("material-entity", "nomenclatural-type"),
        use_when="A Taxon record has explicit specimen or nomenclatural type information.",
        avoid_when="The specimen is only an occurrence with no relationship to a Taxon core record.",
    ),
    DarwinCoreExtensionType.VERNACULAR_NAME: DarwinCoreSchema(
        key="vernacularname",
        title="Vernacular Name",
        spec_uri="https://rs.gbif.org/extension/gbif/1.0/vernacularname.xml",
        local_filename="extensions/vernacularname.xml",
        row_type="http://rs.gbif.org/terms/1.0/VernacularName",
        terms=(
            "countryCode",
            "datasetID",
            "isPlural",
            "isPreferredName",
            "language",
            "lifeStage",
            "locality",
            "locationID",
            "organismPart",
            "sex",
            "source",
            "taxonRemarks",
            "temporal",
            "vernacularName",
        ),
        compatible_cores=("taxon",),
        subject="A vernacular name for a taxon, optionally scoped by language or place.",
        typical_dwc_dp_resources=("taxon",),
        use_when="A Taxon has one or more explicit vernacular names with useful qualifiers.",
        avoid_when="There is only one unqualified vernacularName already represented in the core.",
    ),
    DarwinCoreExtensionType.RELEVE: DarwinCoreSchema(
        key="releve_2016-05-10",
        title="Relevé",
        spec_uri=None,
        local_filename="extensions/releve_2016-05-10.xml",
        row_type="http://rs.gbif.org/terms/1.0/Releve",
        terms=(
            "aspect",
            "coverAlgaeInPercentage",
            "coverCryptogamsInPercentage",
            "coverHerbsInPercentage",
            "coverLichensInPercentage",
            "coverLitterInPercentage",
            "coverMossesInPercentage",
            "coverRockInPercentage",
            "coverShrubsInPercentage",
            "coverTotalInPercentage",
            "coverTreesInPercentage",
            "coverWaterInPercentage",
            "herbLayerHeightInCentimeters",
            "inclinationInDegrees",
            "lichensIdentified",
            "mossesIdentified",
            "project",
            "shrubLayerHeightInMeters",
            "syntaxonName",
            "treeLayerHeightInMeters",
        ),
        compatible_cores=("event",),
        subject="Vegetation plot measurements associated with a survey Event.",
        typical_dwc_dp_resources=("survey", "event-assertion"),
        use_when="An Event-centred vegetation survey explicitly reports registered relevé properties.",
        avoid_when="The event is not a vegetation plot survey or values would be inferred.",
    ),
    DarwinCoreExtensionType.CHRONOMETRIC_AGE: DarwinCoreSchema(
        key="ChronometricAge_2024-03-11",
        title="Chronometric Age",
        spec_uri=None,
        local_filename="extensions/ChronometricAge_2024-03-11.xml",
        row_type="http://rs.tdwg.org/chrono/terms/ChronometricAge",
        terms=(
            "chronometricAgeConversionProtocol",
            "chronometricAgeDeterminedBy",
            "chronometricAgeDeterminedDate",
            "chronometricAgeID",
            "chronometricAgeProtocol",
            "chronometricAgeReferences",
            "chronometricAgeRemarks",
            "chronometricAgeUncertaintyInYears",
            "chronometricAgeUncertaintyMethod",
            "earliestChronometricAge",
            "earliestChronometricAgeReferenceSystem",
            "latestChronometricAge",
            "latestChronometricAgeReferenceSystem",
            "materialDated",
            "materialDatedID",
            "materialDatedRelationship",
            "uncalibratedChronometricAge",
            "verbatimChronometricAge",
        ),
        compatible_cores=("occurrence",),
        subject="A chronometric age determination for dated material represented by an occurrence.",
        typical_dwc_dp_resources=("material-entity", "material-assertion"),
        use_when="Explicit dating results and their method or reference can be linked to an occurrence.",
        avoid_when="Only broad geological context is available or the dated material cannot be resolved.",
    ),
}


ALL_SCHEMAS: Tuple[DarwinCoreSchema, ...] = tuple(CORE_SCHEMAS.values()) + tuple(
    EXTENSION_SCHEMAS.values()
)


def iter_schemas(include_extensions: bool = True) -> Iterable[DarwinCoreSchema]:
    yield from CORE_SCHEMAS.values()
    if include_extensions:
        yield from EXTENSION_SCHEMAS.values()
