import './globals.css'
import { Inter, IBM_Plex_Serif } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import { AuthProvider } from './contexts/AuthContext'
import { ThemeProvider } from './contexts/ThemeContext'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })
const ibmPlexSerif = IBM_Plex_Serif({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: 'ChatIPT',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>ChatIPT</title>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const savedTheme = localStorage.getItem('chatipt-theme');
                  const isAuto = !savedTheme || savedTheme === 'auto';
                  const isDark = isAuto 
                    ? window.matchMedia('(prefers-color-scheme: dark)').matches
                    : savedTheme === 'dark';
                  
                  if (isDark) {
                    document.documentElement.setAttribute('data-bs-theme', 'dark');
                    document.documentElement.classList.add('dark');
                    document.documentElement.classList.remove('light');
                  } else {
                    document.documentElement.setAttribute('data-bs-theme', 'light');
                    document.documentElement.classList.add('light');
                    document.documentElement.classList.remove('dark');
                  }
                } catch (e) {
                  // Fallback to dark theme if there's an error
                  document.documentElement.setAttribute('data-bs-theme', 'dark');
                  document.documentElement.classList.add('dark');
                }
              })();
            `,
          }}
        />
      </head>
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <h1 className={`${ibmPlexSerif.className} title`}>ChatIPT</h1>
            <Header />
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
