"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

# ORCID environment selection: "production" or "sandbox", defaults to production
ORCID_ENV = os.environ.get("ORCID_ENV", "production")

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0").split(",")

# CORS_ALLOWED_ORIGINS = [
#     'http://front-end',
#     'http://localhost:3000',
#     'http://68.183.64.100:3000',
#     'http://68.183.64.100',
# ]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "rest_framework",
    "django_filters",
    "drf_spectacular",
    "corsheaders",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.orcid",
    "api",
    "website",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"

# Custom user model
AUTH_USER_MODEL = "api.CustomUser"

# Site ID for django.contrib.sites
SITE_ID = 1

# Authentication settings
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Allauth settings for API-only approach
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "none"  # ORCID handles email verification
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[ChatIPT] "
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

# Allauth redirect settings for React frontend
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_LOGOUT_REDIRECT_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")
LOGIN_REDIRECT_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")

# Social account settings
SOCIALACCOUNT_PROVIDERS = {
    "orcid": {
        "APP": {
            "client_id": os.environ.get("ORCID_CLIENT_ID"),
            "secret": os.environ.get("ORCID_CLIENT_SECRET"),
            "key": "",
        },
        "SCOPE": [
            "openid",
            "/authenticate",
        ],
    }
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# S3/MinIO Static Files Configuration
# Check if required environment variables are set
MINIO_URI = os.environ.get("MINIO_URI")
MINIO_ACCESS_KEY = os.environ.get("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = os.environ.get("MINIO_SECRET_KEY")
MINIO_BUCKET = os.environ.get("MINIO_BUCKET")
MINIO_STATIC_BUCKET = os.environ.get("MINIO_STATIC_BUCKET", MINIO_BUCKET)
# Use a separate bucket for user files, or same bucket with different location
MINIO_USER_FILES_BUCKET = os.environ.get("MINIO_USER_FILES_BUCKET", MINIO_BUCKET)

if MINIO_URI and MINIO_ACCESS_KEY and MINIO_SECRET_KEY and (MINIO_STATIC_BUCKET or MINIO_BUCKET):
    # Use custom MinIO storage backend
    STATICFILES_STORAGE = "api.storage.MinIOStorage"

    # Local storage path for user files (PVC mount point or local directory)
    USER_FILES_LOCAL_PATH = os.environ.get("USER_FILES_LOCAL_PATH", os.path.join(BASE_DIR, "user_files"))

    # Modern STORAGES configuration (Django 4.2+)
    STORAGES = {
        "default": {
            "BACKEND": "api.storage.DualStorage",
            "OPTIONS": {
                "minio_storage": {
                    "access_key": MINIO_ACCESS_KEY,
                    "secret_key": MINIO_SECRET_KEY,
                    "bucket_name": MINIO_USER_FILES_BUCKET,
                    "endpoint_url": MINIO_URI,
                    "location": "",  # No prefix for user files
                },
                "local_base_path": USER_FILES_LOCAL_PATH,
            },
        },
        "staticfiles": {
            "BACKEND": "api.storage.MinIOStorage",
            "OPTIONS": {
                "access_key": MINIO_ACCESS_KEY,
                "secret_key": MINIO_SECRET_KEY,
                "bucket_name": MINIO_STATIC_BUCKET,
                "endpoint_url": MINIO_URI,
                "location": "static",
            },
        },
    }

    # Static files URL
    STATIC_URL = f"https://{MINIO_URI}/{MINIO_STATIC_BUCKET}/static/"

    print(f"Using S3/MinIO storage for static files: https://{MINIO_URI}/{MINIO_STATIC_BUCKET}")
    print(f"Using dual storage (MinIO + local) for user files:")
    print(f"  - MinIO: https://{MINIO_URI}/{MINIO_USER_FILES_BUCKET}")
    print(f"  - Local: {USER_FILES_LOCAL_PATH}")
else:
    # Fallback to local filesystem if MinIO env vars are missing
    print(
        "Warning: MinIO environment variables not set, using local filesystem for static files"
    )
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
    STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django Rest Framework
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# CORS settings for React frontend
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")
CORS_ALLOWED_ORIGINS = [
    FRONTEND_URL,
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://staging-api.chatipt.svc.gbif.no",
    "https://staging.chatipt.svc.gbif.no",
    "https://chatipt.svc.gbif.no",
    "https://api.chatipt.svc.gbif.no",
]

# Allow credentials (cookies) for session authentication
CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings to ensure headers are always added
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Allow all methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Expose headers that frontend might need
CORS_EXPOSE_HEADERS = [
    'content-type',
    'content-length',
]

# CSRF settings for cross-domain requests
CSRF_TRUSTED_ORIGINS = [
    "https://staging.chatipt.svc.gbif.no",
    "https://chatipt.svc.gbif.no",
    "https://api.chatipt.svc.gbif.no",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://staging-api.chatipt.svc.gbif.no",
]

# Session settings for cross-domain authentication
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"  # Allows cross-site requests with credentials
SESSION_COOKIE_DOMAIN = None  # Allow cookies for all domains
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True  # Save session on every request

# For development, you can use this instead of CORS_ALLOWED_ORIGINS
# CORS_ALLOW_ALL_ORIGINS = True

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
}
