# Development values for publishgpt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}

backEnd:
  replicaCount: 1
  image:
    repository: gbifnorway/publishgpt-back-end
    tag: latest
    pullPolicy: Always
  imagePullSecrets: []
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  autoscaling:
    enabled: false
  nodeSelector: {}
  tolerations: []
  affinity: {}
  volumeMounts: []
  volumes: []
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
  readinessProbe:
    httpGet:
      path: /ready
      port: http
  secretRef:
    name: backend-env-secrets-dev

  service:
    type: ClusterIP
    port: 80
    targetPort: 8000

  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: api.chatipt-dev.svc.gbif.no
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
     - secretName: chatipt-back-end-tls-dev
       hosts:
         - api.chatipt-dev.svc.gbif.no
    securityContext: {}

frontEnd:
  replicaCount: 1
  image:
    repository: gbifnorway/publishgpt-front-end
    tag: latest
    pullPolicy: Always
  imagePullSecrets: []
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  autoscaling:
    enabled: false
  nodeSelector: {}
  tolerations: []
  affinity: {}
  volumeMounts: []
  volumes: []
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
  readinessProbe:
    httpGet:
      path: /ready
      port: http
  env:
    - name: NEXT_PUBLIC_BASE_API_URL
      value: "https://api.chatipt-dev.svc.gbif.no/api"

  service:
    type: ClusterIP
    port: 80
    targetPort: 3000

  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: chatipt-dev.svc.gbif.no
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
     - secretName: chatipt-front-end-tls-dev
       hosts:
         - chatipt-dev.svc.gbif.no
    securityContext: {} 