# Default values for publishgpt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


nameOverride: ""
fullnameOverride: ""


podSecurityContext: {}

backEnd:
  replicaCount: 1
  image:
    repository: gbifnorway/publishgpt-back-end
    tag:
    pullPolicy: Always
  imagePullSecrets: []
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  autoscaling:
    enabled: false
  nodeSelector: {}
  tolerations: []
  affinity: {}
  volumeMounts: []
  volumes: []
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
  readinessProbe:
    httpGet:
      path: /ready
      port: http
  secretRef:
    name: backend-env-secrets

  service:
    type: ClusterIP
    port: 80
    targetPort: 8000

  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: publishgpt-api.svc.gbif.no
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
     - secretName: publishgpt-back-end-tls
       hosts:
         - publishgpt-api.svc.gbif.no
    securityContext: {}


frontEnd:
  replicaCount: 1
  image:
    repository: gbifnorway/publishgpt-front-end
    tag:
    pullPolicy: Always
  imagePullSecrets: []
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  autoscaling:
    enabled: false
  nodeSelector: {}
  tolerations: []
  affinity: {}
  volumeMounts: []
  volumes: []
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
  readinessProbe:
    httpGet:
      path: /ready
      port: http

  service:
    type: ClusterIP
    port: 80
    targetPort: 3000

  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: publishgpt.svc.gbif.no
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
     - secretName: publishgpt-front-end-tls
       hosts:
         - publishgpt.svc.gbif.no
    securityContext: {}

  apiUrl: "https://{{ .Values.backEnd.ingress.hosts[0].host }}/api"
